version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cafe_app
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=change_me_super_secret
      - ULTRA_INSTANCE_ID=${ULTRA_INSTANCE_ID}
      - ULTRA_TOKEN=${ULTRA_TOKEN}
      - ULTRA_PHONE_SENDER=${ULTRA_PHONE_SENDER}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongo_data: